package Extra;
// 1400. Construct K Palindrome Strings

// Solved
// Medium
// Topics
// Companies
// Hint
// Given a string s and an integer k, return true if you can use all the characters in s to construct k palindrome strings or false otherwise.

// Example 1:

// Input: s = "annabelle", k = 2
// Output: true
// Explanation: You can construct two palindromes using all characters in s.
// Some possible constructions "anna" + "elble", "anbna" + "elle", "anellena" + "b"
// Example 2:

// Input: s = "leetcode", k = 3
// Output: false
// Explanation: It is impossible to construct 3 palindromes using all the characters of s.
// Example 3:

// Input: s = "true", k = 4
// Output: true
// Explanation: The only possible solution is to put each character in a separate string.

// Constraints:

// 1 <= s.length <= 105
// s consists of lowercase English letters.
// 1 <= k <= 105
public class ConstructKPalindromeStrings {
    private int countFreq(int[] freq, String s) {
        char[] str = s.toCharArray();
        int count = 0;

        // for(int i = 0; i<str.length;i++){

        // }
        for (char c : str) {
            if (freq[c - 'a'] == 1) {
                freq[c - 'a'] = 0;
                count++;
            } else {
                freq[c - 'a'] = 1;
            }
        }
        return count;
    }

    public boolean canConstruct(String s, int k) {
        if (s.length() < k) {
            return false;
        }
        int[] freq = new int[26];

        int count = countFreq(freq, s);
        int singleCount = 0;
        for (int i = 0; i < freq.length; i++) {
            singleCount = singleCount + freq[i];
        }
        System.out.println(count + " " + singleCount);
        if (singleCount > k) {
            return false;
        }
        if ((count * 2 + singleCount) < k) {
            return false;
        }
        return true;
    }
}
// test cases
// "qlkzenwmmnpkopu"
// 15
// "qlkzenwmmnpkopu"
// 15
// "aabb"
// 3
// "yiipem"
// 3
// "abcdefghijklmnopqrstuvwxyz"
// 25
// "rraceca"
// 3
// "dwhjvyplfsdbgjxqcfvngjsowlmjpkmuasvfvbvvrmnectsrbyfomxskpajfowsnfpkxdmqcifozydqqzeflvdulslyxpyejxjvpnrkqnlrchpzaaaqsxabpgtrssnvtcathbbywnzuszajwpvpqavewpqjxzltijwnpjdhhmezcfaazghlcpylwyylpkncoqlseqizirlxuzlicmezlrbptgmcixhruqtrbtwuebsstsmsttzexdmpkfuukevyepkzmfuetklhbrgkelzrbjteisnujiryfqjqkgoqxevtoqlesrlmzpewhxnngdcmdwxaqyinrxsdvtwepoznsvsybbvqdieffigolowmehabgcmpnxjjjaexvhyesisxoeqvsacwmykfvzxudoiedivyfxyeduoghowpyzatvakmfndewyjobxdscamkhohlybdmnsiawzehtrhktmgtgbarisackxsjvekfdlhsgawsnceauavwzmxtljxssonuwiwftvpjeufqyezgyutfvfsqcqtpkaesibkwxkhhvgtwwoebziplwwttuvpmypqdqjiwcamdlwstprplbunwjcbzkjhpgqjvnhcvpnzyrsvtsmcezkfehxdekjwxjeohwuxljqoyrdvziwflwvgdmwiqtumiubqwjfgouddnhuzxgmdjaujxaxnfdjqatgybqznkutkqakzmkcowibruocgzophvbvfsxdraricdltozvxzppxgbckbyiibpnzhwtebjzudwlshwirltmvmjcitwtysccjcjzjabzkvhclwmufgrtbavgknvvefhozasnodnrjernryytmzkmgobcvckeiqahlnwkaippnrqfmzaimoccnssbrmlmoxknwwpmwiblqdntffdjumbiejzexfgvrrbcqwyqybsehytbssbwtovyeencqirqfhaxtylxxnhvksytmbmttaggtijmoywky"
// 30
// "jicvyghcmoimajglnduqaofybncnhqjltspdmxfayjhkckqzybfrtftlktxriqrhztewahqdwhricmzsbrdfmqlxdqmyizqbbpyrciffjvmyhdsajeltfzvrqhylihmzqafxtzqcwytdwjirprxulapmfsyzxtvyknoyuojsykkpbazofjltgfkqwxevabirswqprbhshytqalxuidbozpunjmjhvvkijqsiqtuwynwkyvmotoprnzdtrltnqpxufjsjqpiyloaaflbuymgscbnlgbieraxxxukaiahgcdzvjrbdhrlvevtxfknexwbflbyblmtkjmhsuimbmnmzleghcsadzluvebninvyecaqemoekuzfdrkkmldymenrgaxgutmxknqtyisumswnqwjedbrfhnpsswazyllymmbpgizoaajgpbpgqtwgzcrzvmppddmzhtmpjkvtxezhbwakikhrevkxevtrhulwfdebxviqsnxsrnrjiklsdnamhetchhkovsqzasqdxqwunddhcrjkxtiavhuhsuzrwjervjihqecoxpsbzbyontpuublomypgkmmobkffeqtcmmwmokqvtaglhihiybsmaueyhfwtowwvetdgipwsnkyvhmwpoehemdysqcsuxlswlhjhoxtgcsbguvyvlcabneiwzxgztcvwnrbofonmmayiyooebjaeuizhxpsolvflvaujlgrdcwsmtpuvfxyxnppnwrwyfqnknavglqxttxemdgyrfizjywhuqikzloydisglmzykkehjzmobpcuzfffgblarallskmzdbcyqhcdjwjmfowunmzosbmbzzxukvfftsfbdejlldetrcwngbrtvesovsyiizqnygvkckdgijvlyanqoyebkefgbgovafwourxinzcytdgfpenglthmmmzmesncotoejiqpmlamzopwndqrxreeksxsidtitcjdllsnrhutulkgqtoxpsgknxxodvhhtgfqeeuxruislmuaueedoqbcvdnqwdshflmayvkcevagvtjynntqgcavooxektxsuxkrhswalvdhwmdffufdsfquoraenkiduonpgjjyqtdqneivfhjfkhddeofstzfshydbcidgvsmqfiqjrmfnxzfdbaqsienfuyejfmcfgqjbedkaomuaqzjvgucudywfahiggvqrzowguyrawliqmuzcymwhkqthyualxpeutpivijyilfqtvuhrynqvdywaexbyfuatywsrxprpywozxiuxsmxpinjvnakrambuofagngtecwfmwuvgyoawzpkyxlrptusjhbrysiisrkqyygvhousljokyrrdelpzzzjmvdajboglfybxehfoyjtobtylkcfuvghdufhsmvgfuhewcyyehdfnbkkuahbbnhyryjrlhuubldduitctbpivimdxosoisxgriaxnyvpokakisxtznyavrssbccvhmgfzlgljpqyoaaqpgecsegtwyvmizfsgvdnhbuqypvogqaagymtewzugdlsikpddqkjozibafmhocrfptfyvwopddlmntcvomsjchhetwqudsekadqtrwvkpljywkshocspreejynixonhdvflpvbqdmllmpysnugglwiiddhxwgivbppybjvusyfrftqunzsqhvlvrddvirfctrrzrkzudhjkclgslzbyfbsqscqvmtnoigkcgxlskdpccagzcccuvliuwmxystoflhbvweqxpliseynangwenzkxlsifktuaehrxhrhrelozibmfmqtbjzbddhnyimnzcsgovljoqxolldcddvcvqvavzyjyhlnvkvhrwdergrgiorjbbjekvtrpqhhcvxeyboslmaygwicyfpnlqqkydwinjzrwttphvnqcjiuwekgqvpwgvnolsbbbkzkaiazdkadvmoibxdwvnyckcqrthydoxqirptwpajtgvnooxozhmulychpgtmamezooplwkaqwyjglkqdnauuximhyltdosuxmfojrljaveozqurksadpfmuewsopdmnijgxqldlxxmhrzymtspvfvvstnvcfofuqvevsakzdpmbyhoayeaggyohzniqbjyvfermsluqzwhzecmganazztsrmakwxcfgswlutpzytxyoriwbhsorocfnqnqnlkvjzmgonocijgwymlolmmddcwcumkjvgssaeuyryzwklgkdxjrvagiwnebhnctaegkvtmiriplkjvqhsysnkjgoucqvfojtjixymhxsntcqpvlvusmvlvojymsmbxvmxderlqnoqxlkacdhduovowkvcglqekndldwgmqyrubmybtpwmoeroyjnglevbtwuejbkihskicqlsfnrkrwgrenawqwwttfpdtfllenuhpywaebqfxoydiamwqbqylcpbbomxodvzpbhwbjqqdnmthxobwnarrdipycxiphvmmkrsclvjaaxwkropsmeyifyephclmlaavurrnlwshlkegouwgbhzmsfwyjalscljjrhgrdijuvxzhvyiqniizilyuaiocxmkrkfkkpfaodauoanfxzxlgxrgfjyxrobskrdwjbbsjnlbcfrmxzzgdkwygxawwtrxwskagltnfgzesobykzjpfcpoydsatvhsckoedwbeztkpoeavlfothdvobuqquefkgnketxlqifcqsrxyhepwdcrncaxnthcxaoopxrwfzppbwfhwgrgvewgescidbwsqjiacsabhpbkuzgqrnxziuxvawztgakeitsahsexgyqqlcmfvsqzmebfwzyycwkmvmvpdesexojbfjvywsuozhlycpshrhxaezjcsfrhhmqfsuffqwdzbqgfyhshnfxmwdhykvmhnxxcjumluszmjylokpxepicmotebyxkgrhkdaunjfpvgmdyorapfvnkrcpysethibkmzbxgatdmksbsoamfwlkdsnqgtmsyajnmouktlulfsdtwjwonaeoaeztrqdmyovjortkpnvrrffugmzxsqfnfavinpiuomdvqbpfmmvwkpxubuftqiphibmkftevrcdornqomrebhclzlgjxszpjegnhuzxfezfmaqcojgfydubevyxcekhrkxxszohvuuyyqshxezhfqebooiioqteawppzgxtfllaepmcqzqmvacpiczulbwozpqolsrwxmtmpmbodyyokiqjupvhdsnyqplozgcidylxbdosfidovutcadtnrugvtyctskbzcpfooqmbbqtvjpekzbvtsznzifdoibhuaeexgtgwqxgpvcbgfmmmjqxgcriguvdinadjbdspiomzakpwuomgtxyouulaywvcdiczonolatslfiaplffwsneeqpealnqswpwcntebbypyvhgbmwhrgalodrifvadulomtmjhfvarlstbdzbzeargwljwgiklmqlopeouediitubhubvoctuumolokkhznmtzmtmmdttsuijcdewuapssbpmqfpltsghzifnctulfmvqbardkuoubdsneydsntuzhjwiomgsagfkcdenvxpbkvmnxhulrwonxdpoocchsylfrvctwytuwdzqlosndffjsleodetmalsnnuhcarhuprywbzzhzddifidwscnpdqlohgkqbxboddzvwrykscisxzzyzumkzjmhtcvzxpzvxmpvudhulkoqqtlnhrlioxhxotgswuqcrkycvigmospqiefibnyileytqkvfbkyaoxnpvnuisogxjzrncqhikfzpvcagjhchmbfcdcqgveagdmfozfxyelnixndlzmoomxkfbcnabnozivyoxmhcughoajpztxyfptkojiybnpxxaxsxwisyimzgvdbyxvfabewuvxhwawdccuhvnjnppsnyeplwuvxdexrviucecpnllpmmpcfcyazvnkxslvdmkzrcierbxcxnahpxuallyujixkwgvyuaiqpvheslzipcjhbhwgvhhotgofrtqfjltbfqnnuggasdmivtbmnhdqestdpdnirydfmizyupymlkpyptdbxsjogpwqknxhgturwuuoqxdnxsxjbfjpbxunogpkkaapmxdxuzmhrewztgagmvxirzwkgikyydkdoztbyslbbsypvnmphzwcjsalvkrsfphbrmzppbegpfftvrkqfwpvqjtkbjlvadpxfnyazufhmgfcsihcmiylaufpwqleizshzgkdtgusrymvrvlpuhneeappvhwfkbgbbbmxzhbeiuiqgdapepnafetgbjrdtcrajqewjiqhtvvthpmkxpxbitgxcqxkysakkdynugeeyhsubhdbaxhgzywhogcqrbprrafdefwujtvlehuhbdaqkxdupcksakcwrppogojbaxnskincjxhgsewnplrwdvmhrxrkvxtmncvqzmpctzdjmgqudfroupeuyqthzmwdwaviydjchryboscstbzjpulnmvktgvgbwncwecjbvyhkfegzlsrexeqedgcezgkdbloulgfonwhykhcdxfnvwnmoqymszmqqoidvabizkbictmpqlhozbjieizpaowspugucteoxvsuwflltfuorydsawjlfoxfcgvojlqurqxbondtubevljbujsfdatlcusmccmhsxagqqprfdcpioygymakztdjwjxovmpdtciyybljqjgydgkcqegeldmlozxlynwtvkpwyqyhiohlbscpbrebbpmxhnnrupxxugqnjqwfeyskefssosjpnbhuwtcqsdvvgqpvsukdfvshxjoioygpxxnpwerqxeskspntkwnrbzmwsxwrvwkdtyhygupbmltsvdpkbphqjhydaceemedkonbbemxkjbmxfgnebhbbxqkzzjegppjikluickomvxtnuxeuparcnitptficmxihrmcvbyhgqshgfjflzcmojfbqiaayuxpqwcpkpfxgwsjpjupwhlmigdqvmronteoukvlvzfhtzfakujlfnszgljoklodvqhxzwmvloqkibblusdrjosfifhcrlfthnrvvmtpqtmuijffdbkcrmjanqglovjggxzltjdxfcxubsyuphhpfvljdgdmfaqoiyqcxggggqrafhaktpljsfssxcszzwzyhdqjpjhfmfatxcsynoeugeievuhhisrylfnxmsbnjusplyqekeodropnnitevippnctkukrkrgdpiitbxezqyxeosrdtbfxdimyrqkywvnpdzciuzqumlozkgqnynkxbiyzfaazdvibjtzhvuooeuxdhnjuudynkuxlqwdnzwakpfzsxxkqnjeragaovyhvqhdsakbuwvvwdqtewjfjnusqfeddxhixtlrpnrjblunqdfzsfhrygrcbjpxfwoymbxymehyivmtgsrtocirskyrdjqwsfsozmyzjsyqeknrrqxtelqpbtcrtxmsqahgxkpxvkoqyncctdfzrzngfxxziplborvxoeqgfoyixppnlrvgdpwiibbfsupqukljrdrsygmqovqhuyhxhwtnyjwddomjxizdxkngpkofxfhqdtwbavqmlnnzjoabzsdfoxkswviwexoqkujhvjizfofpcdctlaohtikrxvjjgtnuqzigshxxqcxkozsbwgyyvbwfauqawasqwiusmpeohiprtptvahfbkhvuvwfvynrpmtrkrhndvwmjcdticabwctzscvfwoorcwzmrmnatxcjnttlcifrjijcqzswtdmpfjfsjsonijfmcujgytsbgsvytfwtfvflsqusmxbfkcrqfbzzneohlixibqvtrujaqgvrdbuagoruwcmqvpsoqpaxglrmijkxyaclcpbfwxeamsrfnjkxobjpkqanewlgifoyaqnisfzzxleqvvdrlavgddcatgpjsmlasrbrxwgndxkfuorkxoiqvvixudosxvasdzrzycvecbhoujqkxryomjvuslodahbetlmlnrphpchcsiqlwqbqhfmobrerigizkczhgxypzbodgjfvwhimjkmjdfskhxnmwfaocsidmfkojerqxedqxfpzcdsoxjgtpjyghruhqayvncuqpvunnxkuntmkejrxlwxomoxmkcimdazavhwlicygroeafblsjehqkqgvaypjhcyumglsroqfdpdvmmppasjnwuludinscdkxigkznnrttezzwuttwwjldvkvphsbxjbbbwinqsiakkalvlclybleneoyxcpfzguoqxmxgqzccwiyveppvdqghfxxncaqsegjqikbxzjscvcwxmjokxbevpwdikukmknkhjeejeikkgsckttmpzcefbvrkrnculppfkmztwdroountdlfqeypkczikjpbzrstrsdwbrbxxyerfvxnslmahyqkxkvhborpprxzdeucqjljwqdzfgpyyjuhywmnclahymmtgdbskqokvecpjlbxyacyvwdrrtitiktgeqncdlgqlmytqprjitfrdchwwamfmoaaigrgkdkxmhbmfiteuqlrwzqnobnonrbqvkwyrshfcxyvwyjrlcmlesljklsqjmvtxrcdruuefhwfskkeadzzozhpznurhexmyrcdvbcndehuzjsigsmerptsjopdbpwfpmaqvagpofzlicvzhhujlxvfbvkipooozbvovaemdvycnnckynwkhmnptmgutivoswhovgkdatsomrfehfatwqtifkjwcumwijovawqbeltravvvxrpzfjznegbwcmcqwzkryarijwlywposiktyfhemtkldxfovhnmzcgavoyusanwrtkqhzgbgqdfdgfitwygsueixmqptsrrwdwmxenlykonnmrfppgdwpyylrlzmqbdhklaolliunjpbfxrwfdfakoltifjvcrnudbgzfvmuqrcgrasvihkvwcujpordbjyeqbossywpwrczlfjvyhmgnbpgnbbtchcbfcqdjomcjmzlsolpcnwswpghrcbbugenyfikalenhntqelsxocdcxpjydfvlskbtzzwzehqvelaqgfoaypkokhhomjygiflvuauqxvrvfhbajczotgqnnhiobfnxhreqxsgnzdqmxbsktuwwzofqazhufkkhztyfjtvpmaqcedsxlkqdemzajnvsczecsffxycufnoxbypdybofclpbaaaohchprlupxvzhsjqkjopnqftievbednmkrcfgqdcotlddbcbxfdlifyeandvisofxkuwckdyimdhpkptufbsshxwskiyslxlajnibuqezzyagizkmlonpkdbsifjswqnkcgovcgdzocsfdpjykxculauqiocksnxdgixgluefbzhdnhzlgstawujlapszfvfemntgbnskubpoyiimliypaibtneayrxwrwwzizgxalfeqohdxjyrrsywqxygvwjgbuseadgorrgikyzsrwkgkoalenpjkokbozzrhzjpcigolnjbvgqwhawjmjrxgilujwteogpiuywijqixiwwckioodrhtljnqcmqjbumxucjmfbhshnfweighcecnbmfrwvdjmlbyltuzbxdcymajolekhuvvpfwaclvhedbtpsvlsrubgegtttabrlzyrdkmkzhkmwlykyxqrqcducvfkmhvsotydejhdqclesgohkbnjyarobhopmunwmhghbgfshcevtgxlqluzxkvgxpsebtqnmqnpjlaqmrhxxqmourisxqcbconlczczxgrlmhpnkcdrynyvnnkgrtvszpqfbfbchxypvzcdkynebypztpoozyeflhvmqcfxhimlcbdxnzatptqhwulysreypoeiyheznvnaavibfedotpkllpebvxjlansxqaqtuwimlvnfaaaqombeamcipnbtaupmhkxonhbdqkwwdjkhokuaoxikjjxwmnwcvuhbzwgnkemwnhmrxlijfyfodldilcictomcivgmdalevudrtdetqhbnixiostbaisqcrklgpzqliuxmamdgujfyvbndnexnjrswsvakwsmisebaolorbhuaiimipygcndhhhdqhvfrkmzezflyrwlhqehwjvzaczakeemayjemkfyttvnoijgdfvhspgvealmxuuvuqrefqvjwweunpeehtzsecxkqauizkbccapqecwxjyngefeuidpcvguintxczhambtnhehnqndbbtxumkcrswkiqpvwgawxhwpfvhywninbamiyqbdmhrbfelmgxpbuytbyzuwbbrhtgrkgcswftipyjjklmuaxysezvwmtcuzwynwgoseheohfrdcvqydzxhcfsfzujoavcbvvdslstxjyendstahtzxozitfnagtfidrflzrvffzqwkohxmsfujcvrffrhqzntrqxdldovzjhunbxlpublccyurynmoqkfqpjnpwkvhemftmdicqppclpvbynvbjlvxhiaqcnupiarkpzgrodohlrgeqberkycramdwxiyivbnlimtkgzpleopkdsswtxipcgacznhdbvkbhxotmojsknmbmxbvhsldetakwnlfjrbjivzzfwphbusvjqmtatzmpseudzolkjlbhmflqbxrsrrbvxnvirpouimaeucfmaruxrokacyxsctpautbrebjwrmyumpjixzhrwumzgvsjjsnbxwptvgstduxsaldgzgveetocbrqmeyfhxxgzvotryqvbebccraehwtbsmeoaywrbkrbskcfwkymnkdjyournljcndjwczzyaqxwzseycgprrxktpfgpofxzrebpxsiyqigltulvlyrtdwqshmurpzwzjyjkordwjmkipwkwqaupwjwqmrwgbbpjvqaxgxhpisshlevjmigpdizsucrjzowhqerzhpoipkzyzxvdjtckvlfyfzflbuqdxkiobwtiacxgvynyumjpprkguikfhpwtvzadjccitvjunyyavgfaetgkdvcjgejkrfpobdkqhcrqucynvwcmeonkmevlbrzabizxionsbahnlmtgptirxtpkrnrphtfabkcbtrfvtjzlaqinvtawpmswjhcnzpmdxzrgvisuiayddrsdkipmnqzifzxcffygfvjbsbvybitcmdlghaomdkaiaivkrtqkslbqfqrfafpqoptlifdfihsaxaxxwqoaqevyhmjbyuqurqgucduwwvajrjuteyrnefpdcozoafnvnnscheiqhelhofrbofqzirfprgrfbrjhuwagqqmvfiacnevojlvyoqtzewhufainogziijfljoojqgqbibixsvgzucpxpnwaxaulpyzxofebjmfygedwbpmwwcpvhmrpcrpnislwnngufzicvzyrivaochnqytdvrwnuzqkwtktzrthoezcoyhfrhkopztajcurkbkacanjugvxxvqryjlymwebfpqmywifdrwfzkxbfcszynhqhjogmtpkpcxdobzjnwibtkrodvgfofkdppzrbdswvmlevkrgvqymlkdiycdlsljlziolhtbpnntkgchjeblknawvpapsgopiraitvnhbyznepfyvytzezzqjkfcnvdbfihetmzfcceokbrumxxeitwwjmcofqxxyhmgstlszqbodfqqkdoaxxdilnvihoksjllqthuzzxugmufhgkydmomiwefbkzivnptrmmhslrdiggbkhpuyinqlxlalqvokdivaueovmryfluvveioyfrsuyiptlzmmlbdtqskeullfcioecskjqrczgbzvqpfkgcuvyqezwafpyxotivuyqjgyeybbxujsrpevkdvdksaspeaidrfejnntjdhzwistzhlhhyezqtthtvszzfyekikwnukvdiwcdsghfgscjfolitmlzregqpcewpfobpqqkrwmzujxlskwmibtqsoyxdlltogwxpzhjoywznhtrmowmapxxfdntozjllhnlryxtjeabhlkqlmmnjxqrozbrajyptfjngytuheoyoaigzqlcpfwbykqkiwtsfkflnccadfvrdcvuhyxyrffhphxzyzxvuhdjejltjqyuzikoyrxuntnhbidtwttpxdtgmjkkdwroihtkxsyhpoteubsxtyvnuioyovvtcbpdyaidjnbsxieduyxgsfrkcfcmgnignlploxhkljgjyfffbmijwclrddokzpazsntvoiqnpykcakcdancglzwtrgohjqwgkiijctvyqxskrafklplqdyqblrhiaavjqk"
// 4659
